# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Shahzor Ahmad/Desktop/simple_count_Vivado/simple_count.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Shahzor Ahmad/Desktop/simple_count_Vivado/simple_count.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {{C:/Users/Shahzor Ahmad/Desktop/simple_count_Vivado/simple_count.srcs/sources_1/new/simple_count.vhd}}
read_xdc {{C:/Users/Shahzor Ahmad/Desktop/simple_count_Vivado/simple_count.srcs/constrs_1/imports/Nexys4_Master_xdc/Nexys4_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Shahzor Ahmad/Desktop/simple_count_Vivado/simple_count.srcs/constrs_1/imports/Nexys4_Master_xdc/Nexys4_Master.xdc}}]

synth_design -top simple_count -part xc7a100tcsg324-1
write_checkpoint -noxdef simple_count.dcp
catch { report_utilization -file simple_count_utilization_synth.rpt -pb simple_count_utilization_synth.pb }
